@api = http://localhost:3000/prospecto

### Obtener todos los datos de la tabla Vacante

GET {{api}}

### Ingresar un Prospecto

POST {{api}}
Content-Type: application/json

{
    "id": "3",
    "nombre": "Kevin",
    "correo": "gucci@gmail.com",
    "fecha_registro": "2023-05-24"
}

### Obtener un Prospecto por su ID

GET {{api}}/2


### Borrar Prospecto por su ID

DELETE {{api}}/2

### Cantidad de Prospectos

{{api}}/count

### Actualizar Prospecto

PUT {{api}}/3
Content-Type: application/json

{
    "id": "3",
    "nombre": "Rodo",
    "correo": "3000@gmail.com",
    "fecha_registro": "2023-06-14"
}